sudo: false
language: python
branches:
  only:
    - master
install:
  - pip install -q $DJANGO
  - pip install -e .
  - pip install coveralls
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
matrix:
  exclude:
    - python: 3.3
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.3
      env: DJANGO="Django>=1.10,<1.11"
    - python: "pypy3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "pypy3"
      env: DJANGO="Django>=1.10,<1.11"
script:
  - coverage run --source django_social_share setup.py test
after_success:
  coveralls
